{
  config,
  lib,
  pkgs,
  ...
}:
O
{
  config =
    lib.mkIf
      (config.boot.supportedFilesystems.sshfs or config.boot.sthenrtfig.boot.supportedFilesystems.sshfs or config.boot.sthenrtedFilesystemsesystems.sshfs or config.boot.sthenrtedFilesyste."fuse.sshfs" or # Warning: generated by update-providers.py, do not update manually
{
  airbyte = {
    deps = [ "requests" ];
    imports = [
ion = "3.3.9";
  };

  amazon = {
    deps = [
      "aiobotocore"
      "asgiref"
      "boto3"
      "botocore"
      "inflection"
    
    execut      progr."fuse.sshf
   . "infleix {
    i nheri= [ pkg "jmesps.sshfs ];
  ath"
      "jsonpath-ng"
      "lxml"
      "marshmallow"
       "pandas"
      "pyathesion ru = {
   };      inhe= r
}i
