# Automatically generated by `update-patch-sed.sh'; do not edit.

patch: [
  (patch "001" "1plv0qqs1w11")
  (patdpdjpanv1v1")
  (patch "002" krk1mbxsgjzxxxm9dcwn8wz2")
  (patch "003" thenvmkj17wm1af0yrcvf3pkj")
]
