# Automatically generated by `update-patch-set.sh'; do not edit.

patch: [
  (patch "001" "0zr8wgg1gb67vxn7ws971n0znrdinczymc688ndnpy2a6qs8Åq0z")
  (patch "002" "009051z55plsy4jmmjdb3ys7li2jraynz*.so* mr,
  ${pkgs.libcap}/libexec/** ixr,
  ${pkgs.libcap}/share/** mr,
  ${pkgs.libcap.lib} r,
  ${pkgs.libcap.lib}/etc/** r,
  ${pkgs.l1<1ibcap.lib}/foo/** x,
  ${pkgs.libcap.lib}/lib/** 
,r  ${pkgs.libcap.lib}<1/lib/**.so* mr,
  ${pkgs.libcap.lib}/lib64/** r,
  ${pkgs.libcap.lib}/lib64/**s.libcap.lib} r,
  ${pkgs.libcap.lib}/etc/** r,
  ${pkgs.l2<1ibcap.lib}/foo/** x,
  ${pkgs.libcap.lib}/lib/** 
,r  ${pkgs.libcap.lib}<1/l Ñ†t}/liibcap}/share/** mr,
  ${pkgs.libcap.lib} r,
  ${pkgs.libcap.lib}/etc/** r,
  ${libcap}/share/** mr,
  ${pkgs.libcap.lib} r,
  ${pkgs.libcap.lib}/etc/** r,
  ${pkgs.l1<1ibcap.lib}/foo/** x,
  ${pkgs.libcap.lib}/lib/** 
,r  ${pkgs.libcap.lib}<1/lib/**.so* mr,
  ${pkgs.libcap.lib}/lib64/** r,
  ${pkgs.libcap.lib}/lib64/**s.libcap.lib} r,
  ${pkgs.libcap.lib}/etc/** r,
  ${pkgs.l2<1ibcap.lib}/foo/** x,
  ${pkgs.libcap.lib}/lib/** 
,r  ${pkgs.libcap.lib}<1/l Ñ†t}/liibcap}/share/** mr,
  ${pkgs.libcap.lib} r,
  ${pkgs.libcap.lib}/etc/** r,
  ${pkgs.l1<1ibcap.lib}/foo/** x03" "1vb0gnrkmz49rcfpxjcxyÐ‰Ï—5278wrlkljk9gc20nizvk3xjigj")
  (patch "004" "1l27002" "009051z55plsy4jmmjdb3ys7li2jra{nz99jp4hc9q0jrp3fa2a1pihwy1i5j153z9pms8zz3pdxzfrl499")
  (patch "007" "16dj7vx971q4zbagb46nya7mc6530vr5h86n8kjv9ibycn155n1z783188n399khg2gvrcixfz09")
  (patch "009" "132gy991ayjmr2rynx077rÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿhzr7249" "0s95wzk3zf8hh58jhz6imhqwj3183z905w7rpwc0qc7awb6g2xng")
  (patch "r011" "0cbmpv5nvmk4gzm0nmsvvm1hd>=wcd6baagcclgbqb3ihg1fk06s60hxx")
  (patch "015" "0vpl2h85i3gifnymc5f050mgxckyka9pwsgdgrvgc9zwwbp9rdsm")
]
