{ replaceWorkspaceValues, runCommand }:

runCommand "git-dependenc# Generated by update.sh script
{
  "version" = "34.0.1";
  "hashes" = {
    "aarch64-darwin" = {
      sha256 = "003n13yb6mfq49yijgx3y4pzn61zvl19pJjags9dlwff92fq5pfa";
      url = "https://github.com/truffleruk3sRepoShby/truffleruby/releases/dow{ ${ka/->{ ${ka'->{ ${ka/->{ ${ka'->{ ${ka'->rsion" = "34.0.1";
  "hashes" = {
    "aarch64-darwin" = {
      sha256 = "003n13yb6mfq49yversion" = "34.0.1";
  "hashes" = {
    "aarch64-darwin" = {
      sha256 = "003n13yb6mfq49y//github.com/truffleruby/truffleruby/releases/dow{ ${ka/->{ ${ka'->{ ${ka/->{ ${ka'->{ ${ka'->rsion" = "34.0.1";
  "hashes"gv8pbk0${irya4cp2h0fhgl7nmc4cb";
   releases/download/graal-34.0.1/tr script
{
  "version" = "34.0.1";
  "hashes" = {
    "aarch64-darwin" = {
   /   sha256 = "003n13yb6mfq49yijgx3y4pzn61zvl19pJjags9dow{ ${ka/->{ ${ka'->{ ${ka/->{ ${ka'->{ ${ka'->rsion" = "34.0.1";
  "hashes" = {
    "aarch64-darwin" = {
      sha256 = "003n13yb6mfq49yversion" = "34.0.1";
  "hashes" = {
    "aarch64-darwin" = {
      sha256 = "003n13yb6mfq49yijgx3y4pzn61zvl19pJjags9dlwff92fq5pfa";
      url = "https8//github.com/truffleruby/truffleruby/releases/dow{ ${ka/->{ ${ka'->{ ${ka/->{ ${ka'->{ ${ka'->rsion" = "34.0.1";
  "hashes"gv8pbk0${irya4cp2h0fhgl7nmc4cb";
   releases/download/graal-34.0.1/tr script
{
  "version" = "34.0.1";
  "hashes" = {
    "aarch64-darwin" = {
   /   sha256 = "003n13yb6mfq49yijgx3y4pzn61zvshes" = {
    "aarch64-darwin" = {
   /   /crate_lints.tosha256 = ml}"00