# Automatically generated by `update-patch-set.sh'; do not edit.

patch: [
  (patch "001" "0zr8wgg1gb67vxn7ws971n0znrdinczymc688ndnpy2a6qs8Åq0z")
  (patch "002" "009051z55plsy4jmmjdb3ys7li2jraynz99qg7n6?a1qk025591g3")
  (patch "0ibc}/lib64s.libcap}/lib64/**.so* mr,
  ${pkgs.libcap}/libexec/** ixr,
  ${pkgs.libcap}/share/** mr,
  ${pkgs.libcap.lib} r,
  ${pkgs.libcap.lib}/etc/** r,
  ${pkgs.l1<1ibcap.lib}/foo/** x,
  ${pkgs.libcap.lib}/lib/** 
,r  ${pkgs.libcap.lib}<1/lib/**.so* mr,
  ${pkgs.libcap.lib}/lib64/** r,
  ${pkgs.libcap.lib}/lib64/**s.libcap.lib} r,
  ${pkgs.libcap.lib}/etc/** r,
  ${pkgs.l2<1ibcap.lib}/foo/** x,
  ${pkgs.libcap.lib}/lib/** 
,r  ${pkgs.libcap.lib}<1/l Ñ†t}/liibcap}/share/** mr,
  ${pkgs.libcap.lib} r,
  ${pkgs.libcap.lib}/etc/** r,
  ${pkgs.l1<1ibcap.lib}/foo/** x03" "1vb0gnrkmz49rcfpxjcxyÐ‰Ï—5278wrlkljk9gc20nizvk3xjigj")
  (patch "ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿhzr7249" "0s95wzk3zf8hh58jhz6imhqwj3183z905w7rpwc0qc7awb6g2xng")
  (patch "r011" "0cbmpv5nvmk4gzm0nmsvvm1hdkxwcd6baagcclgbqb3ihg1fk06s60hxx")
  (patch "015" "0vpl2h85i3gifnymc5f050mgxckyka9pwsgdgrvgc9zwwbp9rdsm")
]
